name: Disable Workflow

on: 
 push:
   branches: [main]

jobs:
  disable:
   runs-on: ubuntu-latest

   steps:
     - name: DisableTask
       run: echo "Disable Workflow Video Devops"
       
       
